server:
  port: 8080

spring:
  profiles:
    active: "csv"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration
payment:
  csv-repository:
    path: classpath:payments.csv